### PR TITLE
Updated for RDoc 2.5 and various best practices

### PR DESCRIPTION
**Pull request by raggi**
This pull request includes a ton of work by Erik Hollensbe to cleanup the code base and implement it for RDoc 2.5. It also includes a bunch of work, including documentation, to use various best practices for the manner of gem integration. It's used by the rdbi projects among others, and should be release ready.

### CODE REVIEW

**Comment by erikh** [comment]
Note that you can see an example at http://hollensbe.org/rdoc/

**Comment by leejarvis** [comment]
+1 for merging this. The gem certainly requires an update and these updates are exactly what it needs.

**Comment by mislav** [comment]
ZOMG

I'll need some time to digest this. Also, which version of RDoc is this against? Pull requests first says 2.5, then 2.3.5

**Comment by erikh** [comment]
it's against 2.5.9 or so, but should still work with .11. The above link is definitely rdoc 2.5. It might just be mislabeled somewhere, apologies if so.

**Comment by raggi** [comment]
my apologies, i had other things in my brain as a wrote it, busy times.

**Comment by raggi** [comment]
@mislav - sorry to be pushy, but it's time to let go. https://github.com/rdoc/hanna-nouveau

**Comment by mislav** [comment]
I'll check it out. Does it work with latest RDoc?

You want me to merge all this into this repo and continue releasing as "Hanna"? Or are you telling me that you're gonna maintain it under the new name now?

**Comment by leejarvis** [comment]
I think this should be maintained as 'Hanna' by anyone willing to continue maintenance added as contrib

**Comment by raggi** [comment]
@mislav ping. time to let go?

**Comment by erikh** [comment]
@raggi for what it's worth, I need to get hanna-nouveau up to speed with rdoc 3.x -- I need some help here as my time (as I imagine yours, so don't consider this a solicitation) is fleeting. If anyone sees this and would like to help, I'm happy to assist on an advisory basis.

**Comment by mislav** [comment]
I would be interested in merging any branch that brings Hanna up to date with current RDoc. Sorry I haven't been active for a long time, nor took action on this pull request, but I didn't use RDoc that much in the meantime.

**Comment by raggi** [comment]
closing branch. over 2 years old.

**Pull request closed without merging**
